### ISSUE TITLE
Install error on Vercel fresh install

### ISSUE THREAD

**Issue by AmirL** [vercel/nextjs-mysql-auth-starter#12] opened 2023-01-11 16:51 UTC
Just tried to install this repo as a new project, and it failed on the first step (on the web interface):
```
Build failed with 3 errors:
19:44:49.842 | vc-file-system:node_modules/uuid/dist/esm-node/md5.js:1:19: ERROR: Could not resolve "crypto"
19:44:49.842 | vc-file-system:node_modules/uuid/dist/esm-node/rng.js:1:19: ERROR: Could not resolve "crypto"
19:44:49.842 | vc-file-system:node_modules/uuid/dist/esm-node/sha1.js:1:19: ERROR: Could not resolve "crypto"

```

<img width="1218" alt="general_view" src="https://user-images.githubusercontent.com/738521/211866792-c860420a-ef55-4c44-a49d-9b6c039ee788.png">

<img width="802" alt="deploy_fail" src="https://user-images.githubusercontent.com/738521/211866419-39d55470-7505-432c-b174-e4d3dc6bce66.png">--

And less critical, but worth to consider warning:
<img width="811" alt="warning" src="https://user-images.githubusercontent.com/738521/211866401-ca66898e-ea37-4bb4-871e-c1fc5672e89d.png">

**Comment by abtonc** [comment] 2023-01-24 23:22
Do you still get this error? I am not able to reproduce it.

**Comment by AmirL** [comment] 2023-01-26 14:15
> Do you still get this error? I am not able to reproduce it.
I just checked with a new project,  and it works correctly now. No idea what was the reason :).

**Comment by steven-tey** [comment] 2023-02-08 04:43
Can't repro this – will close this for now! Thanks for reporting it though!

**Closed by steven-tey** 2023-02-08 04:43 UTC
